---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boutique-test
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: with-sf
  project: default
  source:
    path: applications/boutique
    repoURL: https://github.com/restonlogic/stormforge.git
    targetRevision: HEAD
  syncPolicy:
    automated:  
      prune: true 
      selfHeal: true 
    syncOptions:  
    - CreateNamespace=true
---
