---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: optimize-live
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: stormforge-live
  project: default
  source:
    path: optimize-live
    repoURL: https://github.com/restonlogic/stormforge.git
    targetRevision: HEAD
    plugin: 
      name: argocd-vault-plugin
  syncPolicy:
    automated:  
      prune: true 
      selfHeal: true 
    syncOptions:  
    - CreateNamespace=true
---