kind: Secret
apiVersion: v1
metadata:
  name: optimize-manager
  namespace: stormforge-system
  labels:
    app.kubernetes.io/version: v2.0.13
  annotations:
    avp.kubernetes.io/path: "secret/optimize-pro"
type: Opaque
stringData:
  STORMFORGE_AUTHORIZATION_CLIENT_ID: <clientID>
  STORMFORGE_AUTHORIZATION_CLIENT_SECRET: <clientSecret>
  STORMFORGE_SERVER_IDENTIFIER: https://api.stormforge.io/
  STORMFORGE_SERVER_ISSUER: https://api.stormforge.io/
