apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: optimize
    control-plane: controller-manager
    app.kubernetes.io/version: v2.0.13
  name: optimize-controller-manager
  namespace: stormforge-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: optimize
      control-plane: controller-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: optimize
        control-plane: controller-manager
        app.kubernetes.io/version: v2.0.13
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: optimize-manager
        image: thestormforge/optimize-controller:2.0.13
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 250Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      terminationGracePeriodSeconds: 10
